spring.application.name=springsec

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=bank
spring.datasource.password=bank
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
